<a href="https://colab.research.google.com/github/nds-najam/PyTorch_Tutorial/blob/master/research/Lecture_5_2_pytorch_training_pipeline_using_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [5]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### train test split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
X_train

array([[ 0.78469993,  0.51455447,  0.79133819, ...,  1.05917788,
         3.14947241,  0.14881056],
       [ 0.21591318,  1.05316178,  0.25627922, ...,  0.75051834,
         0.66405922,  0.30058853],
       [-0.08589203, -0.32888166, -0.13469301, ..., -0.81930233,
        -0.90100966, -0.73510501],
       ...,
       [ 0.91819069,  1.18609465,  0.96407377, ...,  1.19256843,
         0.65116472,  2.74596091],
       [-0.39350118,  1.03024232, -0.36346232, ...,  0.90872574,
         0.76399152,  1.06439205],
       [-0.73593402, -0.20511657, -0.75991152, ..., -0.73787205,
        -0.27240321, -1.022828  ]])

In [11]:
y_train

35     M
65     M
149    B
28     M
17     M
      ..
20     B
522    B
72     M
64     M
251    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [12]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
y_train

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0])

### Numpy arrays to PyTorch tensors

In [14]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

In [16]:
y_train_tensor.shape

torch.Size([455])

```
# This is formatted as code
```
### Defining the model with NN Module & Activation Function

In [17]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

### Important Parameters

In [18]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [19]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.linear.weight  -= learning_rate * model.linear.weight.grad
    model.linear.bias     -= learning_rate * model.linear.bias.grad

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7310100197792053
Epoch: 2, Loss: 0.7153525352478027
Epoch: 3, Loss: 0.7063007950782776
Epoch: 4, Loss: 0.7008098363876343
Epoch: 5, Loss: 0.6971680521965027
Epoch: 6, Loss: 0.6944936513900757
Epoch: 7, Loss: 0.6923478245735168
Epoch: 8, Loss: 0.6905145049095154
Epoch: 9, Loss: 0.6888842582702637
Epoch: 10, Loss: 0.6874009966850281
Epoch: 11, Loss: 0.6860332489013672
Epoch: 12, Loss: 0.6847625374794006
Epoch: 13, Loss: 0.6835764646530151
Epoch: 14, Loss: 0.6824662685394287
Epoch: 15, Loss: 0.6814250946044922
Epoch: 16, Loss: 0.6804470419883728
Epoch: 17, Loss: 0.6795272827148438
Epoch: 18, Loss: 0.6786613464355469
Epoch: 19, Loss: 0.6778453588485718
Epoch: 20, Loss: 0.6770758628845215
Epoch: 21, Loss: 0.6763494610786438
Epoch: 22, Loss: 0.6756634712219238
Epoch: 23, Loss: 0.6750150918960571
Epoch: 24, Loss: 0.6744019389152527
Epoch: 25, Loss: 0.673821747303009

In [20]:
model.linear.weight

Parameter containing:
tensor([[-0.0776,  0.0456,  0.0099,  0.0397,  0.1333,  0.0753,  0.0296, -0.2013,
          0.0985, -0.0926, -0.1542,  0.0540,  0.1887, -0.0725, -0.0849,  0.1237,
          0.0635, -0.1021, -0.0964,  0.0369,  0.0985, -0.0109, -0.0878,  0.0018,
         -0.0633,  0.0902, -0.0969,  0.0960,  0.0554, -0.1818]],
       requires_grad=True)

## Evaluation

In [21]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6315789222717285

### Model with NN Module (Activation Function & Loss Function)

In [22]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)
    return out

### Parameters

In [23]:
learning_rate = 0.1
epochs = 25

In [24]:
# define loss function
loss_function = nn.BCELoss()
type(loss_function)

torch.nn.modules.loss.BCELoss

## Training Pipeline

In [25]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.linear.weight  -= learning_rate * model.linear.weight.grad
    model.linear.bias     -= learning_rate * model.linear.bias.grad

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.874149739742279
Epoch: 2, Loss: 0.6301376819610596
Epoch: 3, Loss: 0.4993724226951599
Epoch: 4, Loss: 0.4262182116508484
Epoch: 5, Loss: 0.37948521971702576
Epoch: 6, Loss: 0.3463023900985718
Epoch: 7, Loss: 0.32107579708099365
Epoch: 8, Loss: 0.30100053548812866
Epoch: 9, Loss: 0.28449827432632446
Epoch: 10, Loss: 0.27060192823410034
Epoch: 11, Loss: 0.2586798667907715
Epoch: 12, Loss: 0.24829916656017303
Epoch: 13, Loss: 0.23915114998817444
Epoch: 14, Loss: 0.23100875318050385
Epoch: 15, Loss: 0.22370068728923798
Epoch: 16, Loss: 0.21709464490413666
Epoch: 17, Loss: 0.21108661592006683
Epoch: 18, Loss: 0.20559343695640564
Epoch: 19, Loss: 0.20054757595062256
Epoch: 20, Loss: 0.1958935260772705
Epoch: 21, Loss: 0.19158519804477692
Epoch: 22, Loss: 0.1875837743282318
Epoch: 23, Loss: 0.1838562786579132
Epoch: 24, Loss: 0.1803746372461319
Epoch: 25, Loss: 0.17711450159549713

## Evaluation

In [26]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5323176383972168

### Model with NN Module (Activation Function, Loss Function, optim module)

In [28]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)
    return out

## Parameters

In [29]:
learning_rate = 0.1
epochs = 25

In [30]:
# define loss function
loss_function = nn.BCELoss()
# type(loss_function)

### Training Pipeline

In [31]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6494735479354858
Epoch: 2, Loss: 0.4980691969394684
Epoch: 3, Loss: 0.4181697368621826
Epoch: 4, Loss: 0.36872050166130066
Epoch: 5, Loss: 0.3344722390174866
Epoch: 6, Loss: 0.3090035021305084
Epoch: 7, Loss: 0.28912055492401123
Epoch: 8, Loss: 0.27304044365882874
Epoch: 9, Loss: 0.25968286395072937
Epoch: 10, Loss: 0.2483520805835724
Epoch: 11, Loss: 0.23857799172401428
Epoch: 12, Loss: 0.23003049194812775
Epoch: 13, Loss: 0.22247017920017242
Epoch: 14, Loss: 0.2157188355922699
Epoch: 15, Loss: 0.20964060723781586
Epoch: 16, Loss: 0.2041298896074295
Epoch: 17, Loss: 0.19910310208797455
Epoch: 18, Loss: 0.19449317455291748
Epoch: 19, Loss: 0.19024553894996643
Epoch: 20, Loss: 0.1863151639699936
Epoch: 21, Loss: 0.18266458809375763
Epoch: 22, Loss: 0.17926235496997833
Epoch: 23, Loss: 0.17608170211315155
Epoch: 24, Loss: 0.17309986054897308
Epoch: 25, Loss: 0.17029713094234467

### Evaluation

In [32]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5300092101097107